language: java
jdk:
  - openjdk8

branches:
  only:
    - master # Master Push에서만 CI 실행


# Travis CI 서버의 Maven/Gradle Dependency 캐시 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# Travis CI에서 실행할 명령어
script: "./gradlew clean build"

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIA23FNLQWNY2WMIXWS
    secret_access_key: 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
    bucket: jong-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - pjongwoo92@naver.com
